<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260929170000 extends AbstractMigration
{
    public function getDescription(): string { return 'Create users and PostgreSQL-backed import rate limits'; }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_users_email ON users (email)');
        $this->addSql('CREATE TABLE import_rate_limits (user_id INT NOT NULL, window_started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, request_count INT NOT NULL, PRIMARY KEY(user_id))');
        $this->addSql('ALTER TABLE import_rate_limits ADD CONSTRAINT fk_import_rate_limits_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE import_rate_limits');
        $this->addSql('DROP TABLE users');
    }
}
