<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260929130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create products, product attributes and product images';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE products (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, external_code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, price NUMERIC(12, 2) NOT NULL, discount NUMERIC(5, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PRODUCTS_EXTERNAL_CODE ON products (external_code)');
        $this->addSql('CREATE INDEX idx_products_name ON products (name)');
        $this->addSql('CREATE INDEX idx_products_price ON products (price)');
        $this->addSql('CREATE INDEX idx_products_name_lower ON products (LOWER(name))');

        $this->addSql('CREATE TABLE product_attributes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_id INT NOT NULL, attribute_key VARCHAR(255) NOT NULL, value TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_product_attributes_product ON product_attributes (product_id)');
        $this->addSql('ALTER TABLE product_attributes ADD CONSTRAINT uniq_product_attribute_key UNIQUE (product_id, attribute_key)');
        $this->addSql('ALTER TABLE product_attributes ADD CONSTRAINT fk_product_attributes_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE product_images (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_id INT NOT NULL, url TEXT NOT NULL, path VARCHAR(1024) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_product_images_product ON product_images (product_id)');
        $this->addSql('ALTER TABLE product_images ADD CONSTRAINT uniq_product_image_url UNIQUE (product_id, url)');
        $this->addSql('ALTER TABLE product_images ADD CONSTRAINT fk_product_images_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE product_images');
        $this->addSql('DROP TABLE product_attributes');
        $this->addSql('DROP TABLE products');
    }
}
