<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260929140000 extends AbstractMigration
{
    public function getDescription(): string { return 'Create import jobs and import errors'; }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE import_jobs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, original_filename VARCHAR(255) NOT NULL, stored_path VARCHAR(1024) NOT NULL, status VARCHAR(32) NOT NULL, total_rows INT NOT NULL, processed_rows INT NOT NULL, successful_rows INT NOT NULL, failed_rows INT NOT NULL, fatal_error TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX idx_import_jobs_status ON import_jobs (status)');
        $this->addSql("CREATE TABLE import_errors (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, import_job_id INT NOT NULL, row_number INT DEFAULT NULL, external_code VARCHAR(255) DEFAULT NULL, severity VARCHAR(16) NOT NULL, message TEXT NOT NULL, raw_data JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX idx_import_errors_job ON import_errors (import_job_id)');
        $this->addSql('ALTER TABLE import_errors ADD CONSTRAINT fk_import_errors_job FOREIGN KEY (import_job_id) REFERENCES import_jobs (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE import_errors');
        $this->addSql('DROP TABLE import_jobs');
    }
}
